export default function TermsPage() {
  return (
    <div style={{ maxWidth: 680, margin: '0 auto', padding: '48px 24px 80px', fontFamily: 'var(--font-body)', color: 'var(--marker-text)', lineHeight: 1.7 }}>
      <div style={{ fontFamily: 'var(--font-display)', fontSize: 32, fontWeight: 500, color: 'var(--marker-black)', marginBottom: 8 }}>Terms of Service</div>
      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--marker-mid)', marginBottom: 40 }}>Last updated: July 2026 · Requite</div>

      {[
        { title: '1. Agreement', body: 'By creating an account you agree to these terms. If you do not agree, do not use the service.' },
        { title: '2. Service description', body: 'Requite is a two-sided AI recruitment platform. It provides AI-powered job scoring, CV tailoring, pipeline tracking, and a candidate-employer matching marketplace. It is provided "as is" and is not a recruitment agency or employment service.' },
        { title: '3. Job data sourcing and indexing', body: 'Requite indexes publicly available job listings from third-party sources, including ATS providers (Greenhouse, Lever, Ashby, SmartRecruiters), Adzuna, and the public career pages of companies our users have chosen to track. We score and organise this information for our users; we do not own, republish, or claim any right to the underlying listings. Every job shown clearly states its original source, and applying always takes you to that source directly. We are not the recruiter, employer, or job board for any listing shown, and we do not intermediate the application process. We respect robots.txt and identify our crawler honestly; if you operate a site we crawl and want us to stop, contact support@upstreaminsights.co.uk and we will act promptly.' },
        { title: '4. AI-generated content', body: 'Scores, CV rewrites, cover letters, and interview prep packs are generated by AI (Anthropic Claude). They are provided for informational purposes only and do not constitute professional career advice. You are responsible for reviewing all AI-generated content before use.' },
        { title: '5. Acceptable use', body: 'You must not: use the service for any unlawful purpose; attempt to circumvent usage limits; resell or redistribute access; upload content that infringes third-party intellectual property rights.' },
        { title: '6. Free tier and paid plans', body: 'Free tier access is subject to usage limits. Paid plans are billed monthly or annually. Subscriptions auto-renew unless cancelled. Refunds are available within 7 days of initial purchase or renewal.' },
        { title: '7. Data and privacy', body: 'We process your data in accordance with our Privacy Policy. You retain ownership of all CV and profile data you upload.' },
        { title: '8. Limitation of liability', body: 'To the maximum extent permitted by law, Requite is not liable for any indirect, incidental, special, or consequential damages arising from your use of the service. Our total liability is limited to the amount you paid in the 12 months before the claim.' },
        { title: '9. Termination', body: 'We may suspend or terminate access for breach of these terms. You may delete your account at any time via Settings.' },
        { title: '10. Governing law', body: 'These terms are governed by the laws of England and Wales. Disputes will be subject to the exclusive jurisdiction of the English courts.' },
        { title: '11. Contact', body: 'For terms queries: support@upstreaminsights.co.uk' },
      ].map(({ title, body }) => (
        <div key={title} style={{ marginBottom: 28 }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 17, fontWeight: 500, color: 'var(--marker-black)', marginBottom: 8 }}>{title}</div>
          <div style={{ fontSize: 14 }}>{body}</div>
        </div>
      ))}

      <div style={{ marginTop: 48, paddingTop: 24, borderTop: '1px solid var(--marker-border)' }}>
        <a href="/" style={{ fontSize: 13, color: 'var(--marker-mid)' }}>← Back to Requite</a>
      </div>
    </div>
  )
}
