export default function TermsPage() {
  return (
    <div style={{ maxWidth: 680, margin: '0 auto', padding: '48px 24px 80px', fontFamily: 'var(--font-body)', color: 'var(--marker-text)', lineHeight: 1.7 }}>
      <div style={{ fontFamily: 'var(--font-display)', fontSize: 32, fontWeight: 500, color: 'var(--marker-black)', marginBottom: 8 }}>Terms of Service</div>
      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--marker-mid)', marginBottom: 40 }}>Last updated: May 2026 · Marker (marker.work)</div>

      {[
        { title: '1. Agreement', body: 'By creating an account you agree to these terms. If you do not agree, do not use the service.' },
        { title: '2. Service description', body: 'Marker is a job search management tool. It provides AI-powered job scoring, CV tailoring, and pipeline tracking. It is provided "as is" and is not a recruitment agency or employment service.' },
        { title: '3. AI-generated content', body: 'Scores, CV rewrites, cover letters, and interview prep packs are generated by AI (Anthropic Claude). They are provided for informational purposes only and do not constitute professional career advice. You are responsible for reviewing all AI-generated content before use.' },
        { title: '4. Acceptable use', body: 'You must not: use the service for any unlawful purpose; attempt to circumvent usage limits; resell or redistribute access; upload content that infringes third-party intellectual property rights.' },
        { title: '5. Free tier and paid plans', body: 'Free tier access is subject to usage limits. Paid plans are billed monthly or annually. Subscriptions auto-renew unless cancelled. Refunds are available within 7 days of initial purchase or renewal.' },
        { title: '6. Data and privacy', body: 'We process your data in accordance with our Privacy Policy. You retain ownership of all CV and profile data you upload.' },
        { title: '7. Limitation of liability', body: 'To the maximum extent permitted by law, Marker is not liable for any indirect, incidental, special, or consequential damages arising from your use of the service. Our total liability is limited to the amount you paid in the 12 months before the claim.' },
        { title: '8. Termination', body: 'We may suspend or terminate access for breach of these terms. You may delete your account at any time via Settings.' },
        { title: '9. Governing law', body: 'These terms are governed by the laws of England and Wales. Disputes will be subject to the exclusive jurisdiction of the English courts.' },
        { title: '10. Contact', body: 'For terms queries: hello@marker.work' },
      ].map(({ title, body }) => (
        <div key={title} style={{ marginBottom: 28 }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 17, fontWeight: 500, color: 'var(--marker-black)', marginBottom: 8 }}>{title}</div>
          <div style={{ fontSize: 14 }}>{body}</div>
        </div>
      ))}

      <div style={{ marginTop: 48, paddingTop: 24, borderTop: '1px solid var(--marker-border)' }}>
        <a href="/" style={{ fontSize: 13, color: 'var(--marker-mid)' }}>← Back to Marker</a>
      </div>
    </div>
  )
}
