export default function TermsPage() {
  return (
    <div style={{ maxWidth: 680, margin: '0 auto', padding: '48px 24px 80px', fontFamily: 'var(--font-body)', color: 'var(--marker-text)', lineHeight: 1.7 }}>
      <div style={{ fontFamily: 'var(--font-display)', fontSize: 32, fontWeight: 500, color: 'var(--marker-black)', marginBottom: 8 }}>Terms of Service</div>
      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--marker-mid)', marginBottom: 40 }}>Last updated: September 2026 · Requite</div>

      {[
        { title: '1. Agreement', body: 'By creating an account you agree to these terms. If you do not agree, do not use the service.' },
        { title: '2. Service description', body: 'Requite is a job-search tool for candidates. It indexes and scores publicly advertised roles, and provides CV tailoring, interview preparation and pipeline tracking. An employer-facing side exists in the software but is not live: there are no employers on the platform, no candidate-employer matching is taking place, and no introductions are being made. If that changes, these terms will be updated and you will be told before it affects you. The service is provided "as is" and is not a recruitment agency or employment service.' },
        { title: '3. Job data sourcing and indexing', body: 'Requite indexes publicly available job listings from third-party sources, including ATS providers (Greenhouse, Lever, Ashby, SmartRecruiters), Adzuna, and the public career pages of companies our users have chosen to track. We score and organise this information for our users; we do not own, republish, or claim any right to the underlying listings. Every job shown clearly states its original source, and applying always takes you to that source directly. We are not the recruiter, employer, or job board for any listing shown, and we do not intermediate the application process. We respect robots.txt and identify our crawler honestly; if you operate a site we crawl and want us to stop, contact support@upstreaminsights.co.uk and we will act promptly.' },
        { title: '4. AI-generated content', body: 'Scores, CV rewrites, cover letters, and interview prep packs are generated by AI (Anthropic Claude). They are provided for informational purposes only and do not constitute professional career advice. You are responsible for reviewing all AI-generated content before use.' },
        { title: '5. Acceptable use', body: 'You must not: use the service for any unlawful purpose; attempt to circumvent usage limits; resell or redistribute access; upload content that infringes third-party intellectual property rights. The Referrals feature lets you record details of people in your own professional network; those details are stored in your browser and not on our servers. Only add people you genuinely know, keep the detail to what is needed to write a message, and do not record anything sensitive about them.' },
        { title: '6. Free tier and paid plans', body: 'Free tier access is subject to usage limits, which are published on the pricing page. Paid plans are billed monthly. Subscriptions auto-renew unless cancelled, and you can cancel at any time from Settings. Refunds are available within 7 days of initial purchase or renewal. Nothing in this clause removes any right you have under consumer law.' },
        { title: '7. Data and privacy', body: 'We process your data in accordance with our Privacy Policy, which lists every company that processes data on our behalf and explains what leaves the UK and why. You retain ownership of all CV and profile data you upload. Using the AI features means sending the relevant parts of your profile to our AI provider; the Privacy Policy sets out exactly which features do this.' },
        { title: '8. Limitation of liability', body: 'To the maximum extent permitted by law, Requite is not liable for any indirect, incidental, special, or consequential damages arising from your use of the service. Our total liability is limited to the amount you paid in the 12 months before the claim.' },
        { title: '9. Termination', body: 'We may suspend or terminate access for breach of these terms. You may delete your account at any time via Settings.' },
        { title: '10. Governing law', body: 'These terms are governed by the laws of England and Wales. Disputes will be subject to the exclusive jurisdiction of the English courts.' },
        { title: '11. Contact', body: 'For terms queries: support@upstreaminsights.co.uk' },
      ].map(({ title, body }) => (
        <div key={title} style={{ marginBottom: 28 }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 17, fontWeight: 500, color: 'var(--marker-black)', marginBottom: 8 }}>{title}</div>
          <div style={{ fontSize: 14 }}>{body}</div>
        </div>
      ))}

      <div style={{ marginTop: 48, paddingTop: 24, borderTop: '1px solid var(--marker-border)' }}>
        <a href="/" style={{ fontSize: 13, color: 'var(--marker-mid)' }}>← Back to Requite</a>
      </div>
    </div>
  )
}
