export const articles = [
  {
    slug: 'flexible-working-lie',
    title: 'How to spot a "flexible working" lie in a job posting',
    subtitle: 'The phrases that mean nothing, the ones that mean everything, and the question that cuts through all of it.',
    date: '2026-05-12',
    readTime: 5,
    excerpt: 'Every posting says it. Almost none of them mean it. Here\'s how to tell the difference before you waste three rounds of interviews finding out the hard way.',
    accent: '#5090f0',
    accentLight: '#EEF4FF',
    heroPattern: 'blue',
    tags: ['Job hunting', 'Red flags', 'WLB'],
    content: [
      { type: 'lead', text: 'You\'ve read the phrase a hundred times. "We offer flexible working arrangements." You\'ve also lived through what it really means at three different companies: a 09:30 start instead of 09:00, if you ask nicely. The gap between the posting and the reality of flexible working is one of the most reliable sources of misery in the modern job market.' },
      { type: 'h2', text: 'The phrases that have been drained of meaning' },
      { type: 'p', text: '"Flexible working" now appears in 74% of senior job postings in the UK, according to Timewise\'s 2024 Power Part Time Index. It has become the HR equivalent of "competitive salary" (a signal that someone in the comms team has read a think-piece about talent attraction, not a description of how the business actually operates.' },
      { type: 'p', text: 'The following phrases are reliably meaningless unless backed up by something concrete:' },
      { type: 'list', items: ['"We trust our people") every company says this. The question is what happens on a Tuesday afternoon when someone actually needs to leave at 3pm.', '"Hybrid working" (hybrid can mean two days a week from home or two days a month. It contains no information.', '"We offer flexible hours") flexible within what band? Core hours of 10–4? Or genuinely output-focused?', '"Work-life balance is important to us" (this one is actually slightly worse than saying nothing, because it suggests the company is aware there\'s a problem.'] },
      { type: 'h2', text: 'The phrases that actually mean something' },
      { type: 'p', text: 'Good signals are usually specific. Look for:' },
      { type: 'list', items: ['"We have no core hours") this is rare and meaningful.', '"We have a results-only work environment" (even rarer, but real.', '"X% of our senior team works compressed hours / four-day weeks / part-time") data points about actual practice rather than aspiration.', '"Async-first" (particularly meaningful in tech and digital roles. It implies the company has actually rethought how communication works, not just allowed people to sit in their kitchen for meetings.'] },
      { type: 'quote', text: 'The best signal is specificity. Vague language almost always means vague practice. When a company can describe exactly how flexible working functions) who does it, what the norms are, how decisions get made remotely (that tells you they\'ve actually built it.' },
      { type: 'h2', text: 'The question that cuts through everything' },
      { type: 'p', text: 'In any first or second-round interview, ask this: "Can you tell me about someone senior) Director level or above (who works a non-standard schedule, and how that works in practice?"' },
      { type: 'p', text: 'You\'re not asking "do you allow flexible working." You\'re asking for evidence that it exists at the level you\'re joining. Companies that genuinely operate flexibly can answer this immediately. They\'ll name someone, describe their setup, and tell you how it works.' },
      { type: 'p', text: 'Companies that don\'t can\'t answer it. They\'ll pause, say something about reviewing it after your probation period, and tell you that they "really encourage people to find what works for them." This is your answer.' },
      { type: 'h2', text: 'What to do before the interview' },
      { type: 'p', text: 'Glassdoor\'s work-life balance score is imperfect but directional. A score below 3.5 is a reliable warning sign. Between 3.5 and 4.0 is average. Above 4.2 at scale (1,000+ reviews) is genuinely unusual and worth investigating.' },
      { type: 'p', text: 'More useful: look at the qualitative reviews and filter for people in roles similar to yours. "As a manager, I found the hours expectations..." is more useful than an aggregate star rating from a mixed workforce.' },
      { type: 'stat', label: '74%', detail: 'of senior UK job postings mention "flexible working") up from 51% in 2020' },
      { type: 'h2', text: 'The polite but clear position to take' },
      { type: 'p', text: 'If flexible working is genuinely important to you, don\'t treat it as something to negotiate after you\'ve already said yes. It belongs in the second round, alongside salary. "One thing that matters to me is X (how does that work here?" is a completely reasonable question for someone at Director level or above.' },
      { type: 'p', text: 'A company that reacts poorly to the question is also answering it.' },
      { type: 'cta', text: 'Requite scores every role you\'re considering against what actually matters) including office days, Glassdoor WLB ratings, and verified parental leave. Start free.' },
    ],
  },

  {
    slug: 'salary-question-senior-hires',
    title: 'The salary question nobody tells senior hires to ask',
    subtitle: 'It\'s not "what\'s the range." It\'s something much more useful (and almost no one asks it.',
    date: '2026-05-05',
    readTime: 6,
    excerpt: 'Salary negotiation advice for experienced people is mostly recycled graduate guidance with a bigger number on it. Here\'s what actually works at Director level and above.',
    accent: '#50c878',
    accentLight: '#EDFCF3',
    heroPattern: 'green',
    tags: ['Salary', 'Negotiation', 'Senior careers'],
    content: [
      { type: 'lead', text: 'The standard negotiation advice) research market rates, anchor high, pause after you name your number (is fine as far as it goes. But most of it was written for people in their late twenties negotiating their second job. Senior hiring works differently. The leverage is different, the information asymmetry is different, and the questions that actually get you somewhere are different.' },
      { type: 'h2', text: 'What "the band" actually means' },
      { type: 'p', text: 'Every hiring manager has a band. Bands are wider than you think) typically 20–35% from floor to ceiling at senior level. The number they offer you is almost never the ceiling. It\'s usually 15–25% below it, because they expect negotiation and because starting below the ceiling gives them room to give you a pay rise in year two without restructuring the grade.' },
      { type: 'p', text: 'The standard question ("what\'s the salary range for this role?") is useful but reveals the ceiling without telling you where you sit relative to your peers. The more useful question is different.' },
      { type: 'h2', text: 'The question to ask instead' },
      { type: 'quote', text: '"If I joined and performed to expectations in year one, where would I expect to sit within the band (and how does that compare to the team I\'d be joining or leading?"' },
      { type: 'p', text: 'This question does several things at once. It signals that you\'re thinking about the long term, not just the starting number. It forces them to reveal how they position the role internally. And it tells you whether you\'d be walking in as the lowest-paid person at your level, which is relevant both financially and politically.' },
      { type: 'p', text: 'The answer also tells you something about the culture. Companies that can answer this clearly have thought about pay equity and internal progression. Companies that become evasive are often sitting on a messy legacy pay structure where the new person earns more than someone who\'s been there eight years) which creates a specific kind of social friction you should know about before you join.' },
      { type: 'h2', text: 'The total comp conversation most people skip' },
      { type: 'p', text: 'At Director level and above, base salary is often not the most variable element of a package. Bonus structure, equity, pension matching, and benefits (particularly parental leave for those who need it) can add 20–40% to the effective value of the role.' },
      { type: 'p', text: 'The mistake most people make is treating these as separate negotiations. They\'re not. The right approach is to think about a total compensation floor and be explicit about it: "My current package including base, bonus, and pension is £X. I\'m looking to move that number, not shuffle it around between columns."' },
      { type: 'stat', label: '32%', detail: 'of senior professionals accepted a role without negotiating the initial offer, according to LinkedIn\'s 2024 Opportunity Index' },
      { type: 'h2', text: 'When to have this conversation' },
      { type: 'p', text: 'Before the third round. Not as the first thing you say, but definitely before you\'ve completed two rounds of their process. Finding out in the offer stage that the ceiling of their band is 15% below your floor is an avoidable waste of everyone\'s time.' },
      { type: 'p', text: 'A recruiter or talent partner (not the hiring manager) is the right person to have this conversation with initially. They\'re paid to close the role and have more flexibility to give you real information.' },
      { type: 'h2', text: 'The counter-offer trap' },
      { type: 'p', text: 'If you get an offer and use it to extract a counter-offer from your current employer, be clear-eyed about what you\'re doing. Research consistently shows that people who accept counter-offers leave within 18 months in the majority of cases. The reasons you wanted to leave don\'t change (they just get temporarily papered over with money.' },
      { type: 'p', text: 'The better use of an outside offer is as information: it tells you what the market thinks you\'re worth. If your current employer\'s counter makes you want to stay, the more interesting question is why they weren\'t paying you that already.' },
      { type: 'cta', text: 'Requite estimates market salary for every role you score) based on real Adzuna data, not a survey from 2022. Start free.' },
    ],
  },

  {
    slug: 'evenings-cost-more-than-you-think',
    title: 'Your evenings cost more than you think',
    subtitle: 'A quiet calculation about what overwork actually takes from you (and how to do the maths before you accept another role that demands them.',
    date: '2026-04-28',
    readTime: 7,
    excerpt: 'The opportunity cost of working late is rarely calculated honestly. Here\'s what happens when you try.',
    accent: '#d84888',
    accentLight: '#FEF0F6',
    heroPattern: 'pink',
    tags: ['Work-life balance', 'Career', 'Wellbeing'],
    content: [
      { type: 'lead', text: 'Nobody thinks of themselves as someone who trades their evenings for money. They think of themselves as someone who cares about their work, who has high standards, who is building something. This framing is useful to employers and genuinely felt by employees. It is also, in aggregate, one of the most expensive beliefs a senior professional can hold.' },
      { type: 'h2', text: 'The arithmetic that doesn\'t get done' },
      { type: 'p', text: 'Let\'s take a conservative example. A Director earning £110,000 who regularly works 50 hours a week instead of the nominal 37.5 is effectively providing 12.5 hours of free labour per week. Over a working year of 46 weeks, that\'s 575 hours) roughly 15 extra working weeks per year.' },
      { type: 'p', text: 'At their implied hourly rate, those 575 hours represent approximately £30,000 of labour provided free of charge. This is not a fringe edge case. It describes most senior hires in UK professional services, media, and tech.' },
      { type: 'quote', text: 'The most expensive thing you\'ll ever give your employer isn\'t your skills or your judgment. It\'s your attention, unconditionally, for decades. And unlike money, you can\'t earn it back.' },
      { type: 'h2', text: 'What those hours actually displace' },
      { type: 'p', text: 'The economic framing matters, but it understates the cost. The hours between 6pm and 10pm are not neutral time that would otherwise be spent staring at a wall. They are when people exercise, when they have uninterrupted conversations with partners, when they put children to bed, when they maintain the friendships that become harder to rebuild at 45 than they were at 35.' },
      { type: 'p', text: 'Research from the Work Foundation at Lancaster University found that people who consistently work more than 48 hours per week report 30% lower scores on measures of relationship quality after two years (and that the effect compounds. The people whose relationship with their own life gradually erodes are not typically those who made a conscious trade. They\'re usually the ones who told themselves it was temporary.' },
      { type: 'stat', label: '15 weeks', detail: 'of unpaid overtime provided by the average senior UK professional per year) equivalent to working a 13th and 14th month' },
      { type: 'h2', text: 'The role that looks the same but isn\'t' },
      { type: 'p', text: 'Two Director-level roles at similar companies, both paying £115,000, can have entirely different implicit contracts. One expects 45 hours. The other expects 55. The difference over a ten-year career is roughly 2,300 hours (about 58 additional working weeks of your life.' },
      { type: 'p', text: 'This is not reflected in the job posting. It is almost never discussed in the interview. It is usually discovered in the first 90 days, after the decision has been made.' },
      { type: 'h2', text: 'How to find out before you commit' },
      { type: 'p', text: 'Ask people who have left the company, not people who are still there. Glassdoor reviews from ex-employees, former colleagues on LinkedIn, or recruiter networks are more reliable than anything you\'ll hear in an interview.' },
      { type: 'p', text: 'Ask the hiring manager what time they typically finish work on a weekday. This is not an inappropriate question at Director level. The answer, and the hesitation before it, is usually informative.' },
      { type: 'p', text: 'Ask what the expectation is around evening email. "Do people tend to respond to messages sent after 7pm?" is low-stakes enough to ask but high-signal enough to be worth it.' },
      { type: 'h2', text: 'The version of this that goes well' },
      { type: 'p', text: 'The best outcome is not zero hours of overwork forever. It\'s conscious choice) knowing what you\'re trading, for what period, and for what reason. Three intense months to launch a product is different from a structurally demanding role that will consume your next five years.' },
      { type: 'p', text: 'The people who navigate this best are not the ones who refuse to work hard. They\'re the ones who are precise about what they\'re signing up for, and who treat a job that quietly takes their evenings as what it is: a pay cut.' },
      { type: 'cta', text: 'Requite scores every role you\'re considering on eight factors (including office days and culture signals that indicate how hard a company actually works its people.' },
    ],
  },

  {
    slug: 'cv-costing-you-interviews',
    title: 'Your CV is probably three years out of date. Here\'s how to fix it this weekend.',
    subtitle: 'The specific mistakes senior professionals make on their CVs) and the ones that matter most for getting past the first screen.',
    date: '2026-04-21',
    readTime: 6,
    excerpt: 'Senior CVs have a specific, predictable set of problems that have nothing to do with your actual career. Most of them can be fixed in a few hours.',
    accent: '#e8c830',
    accentLight: '#FEFBEC',
    heroPattern: 'yellow',
    tags: ['CV', 'Job applications', 'Career'],
    content: [
      { type: 'lead', text: 'The most common CV problem among experienced professionals is not a gap, a career change, or a difficult stint they don\'t know how to explain. It\'s something more mundane: the document hasn\'t been meaningfully updated since the last time they needed it, which was three years ago, for a role that was nothing like what they\'re applying for now.' },
      { type: 'h2', text: 'The problem with a CV that was written for a different job' },
      { type: 'p', text: 'When you last updated your CV, you were going for a specific kind of role. The language you used (the emphasis, the order of bullet points, the skills you highlighted) was calibrated for that. It may have worked. But that optimisation is now invisible to you and completely unhelpful for the job you\'re applying for today.' },
      { type: 'p', text: 'This is the most common structural problem: the CV is accurate but it\'s telling the wrong story. A Head of Partnerships whose CV leads with sales metrics and pipeline numbers is telling a different story than one whose CV leads with commercial strategy and stakeholder relationships (even if both descriptions apply to the same person.' },
      { type: 'h2', text: 'The five senior CV mistakes, in order of how much they hurt you' },
      { type: 'p', text: '1. Leading with responsibilities, not outcomes. "Managed a team of 12" tells a reader almost nothing useful. "Restructured a team of 12 to reduce time-to-hire by 40%" tells them what you actually achieved. Senior CVs should be 70% outcomes and 30% context.' },
      { type: 'p', text: '2. Not updating the skills section for the current moment. If your CV doesn\'t mention AI tools, data literacy, or whatever the relevant current capability is for your function, it reads as out of date) even if the rest of it is current.' },
      { type: 'p', text: '3. Burying the most impressive thing. Most people put their most recent role first and their most impressive achievement wherever it happened to occur chronologically. That might mean a significant commercial win is sitting on page two, where it will never be read.' },
      { type: 'p', text: '4. A personal statement that sounds like everyone else\'s. "A strategic and commercially-minded leader with 15 years of experience..." is not a personal statement. It is a sentence that describes a substantial fraction of the professional population. If your first sentence could appear on five other people\'s CVs unchanged, rewrite it.' },
      { type: 'p', text: '5. Wrong length. One page for junior. Two pages for mid-level. Two tight pages for senior. Not three, not four, not "I have a lot to say." Hiring managers at Director level and above spend 30-45 seconds on a first pass.' },
      { type: 'quote', text: 'The CV question to ask yourself is not "does this accurately represent my career?" It\'s "does this make someone want to meet me within 45 seconds?" Those are different documents.' },
      { type: 'h2', text: 'The one thing to fix first if you only have an hour' },
      { type: 'p', text: 'Read the first three bullet points under each role and ask: would someone reading this know what changed because of me being there? If the answer is no (if the bullets describe what the role involved rather than what you specifically achieved) that\'s your priority. Rewrite those six to nine bullet points with outcomes and numbers, even rough ones.' },
      { type: 'h2', text: 'The role-specific version of your CV' },
      { type: 'p', text: 'The highest-performing senior candidates don\'t have one CV. They have a base document and they spend 20–30 minutes before each application adjusting the language to match the specific role. This sounds like a lot of work. It is less work than three rounds of interviews for a role you don\'t get.' },
      { type: 'stat', label: '45 seconds', detail: 'average time spent on a senior CV in a first-pass screen, according to eye-tracking research from Ladders Inc' },
      { type: 'h2', text: 'What to do this weekend' },
      { type: 'p', text: 'Saturday morning: read through your CV as if you\'re a hiring manager who doesn\'t know you. Mark every bullet point that describes a responsibility (what you did) rather than an outcome (what changed). Rewrite them.' },
      { type: 'p', text: 'Saturday afternoon: rewrite your personal statement. Make it specific. If you can put someone else\'s name on it without changing a word, start again.' },
      { type: 'p', text: 'Sunday: run it through a spell check, a readability check, and then ask a peer in your field to read it and tell you what they think you do for a living. If their answer isn\'t what you want them to think, you\'re not done.' },
      { type: 'cta', text: 'Requite can generate a tailored CV prompt for any role in your pipeline (one that rewrites your profile to match the specific JD, in your voice. Start free.' },
    ],
  },

  {
    slug: 'glassdoor-metric-predicts-burnout',
    title: 'The one Glassdoor metric that actually predicts burnout',
    subtitle: 'It\'s not the overall star rating. It\'s not the CEO approval score. It\'s something most people skip entirely.',
    date: '2026-04-14',
    readTime: 5,
    excerpt: 'Glassdoor contains a lot of noise. But buried in the data is a single number that correlates more strongly with the actual working experience than anything else on the page.',
    accent: '#a060d8',
    accentLight: '#F6F0FF',
    heroPattern: 'purple',
    tags: ['Research', 'Burnout', 'WLB', 'Data'],
    content: [
      { type: 'lead', text: 'Glassdoor reviews are simultaneously one of the most useful and most abused sources of workplace intelligence available to job seekers. Most people look at the overall rating and the most recent reviews. This is the right instinct badly executed. The signal is real) but it\'s not in the place most people look for it.' },
      { type: 'h2', text: 'Why the overall rating is the least useful number on the page' },
      { type: 'p', text: 'The overall Glassdoor rating conflates things that matter for your quality of life with things that don\'t, or matters differently. Compensation and benefits satisfaction, for instance, inflates overall scores at banks and consultancies where people are well paid but routinely work 70-hour weeks. Culture and values scores can be high at companies where the values are genuinely held but the workload is unsustainable.' },
      { type: 'p', text: 'The overall rating at Goldman Sachs UK is higher than at many companies in the creative industries where people work considerably shorter hours. A raw average across factors that have different relevance to your situation is a noisy signal at best.' },
      { type: 'h2', text: 'The metric that actually matters' },
      { type: 'quote', text: 'It\'s the Work-Life Balance sub-score, specifically: how it has trended over the last 12 months, and how it compares to the industry average at the same revenue scale.' },
      { type: 'p', text: 'The WLB sub-score (called "Work/Life Balance" in Glassdoor\'s breakdown) correlates more strongly with self-reported burnout, turnover intention, and reported stress levels than any other Glassdoor metric in independent academic studies. It is also the metric companies are most reluctant to address publicly, because improving it often requires changing how the business actually operates (not just writing better HR copy.' },
      { type: 'h2', text: 'The trend matters more than the number' },
      { type: 'p', text: 'A WLB score of 3.8 that has risen from 3.2 over 18 months tells a different story than a 3.8 that has fallen from 4.4. The first suggests a company actively working on the problem. The second suggests one that had something good and lost it) usually through rapid growth, a leadership change, or a strategic pivot that increased pressure without increasing headcount.' },
      { type: 'p', text: 'Glassdoor doesn\'t display trends prominently. You have to look at the reviews chronologically and mentally map the scores over time, or use third-party tools that do this aggregation.' },
      { type: 'stat', label: '4.2', detail: 'Work-life balance sub-score that Requite treats as the threshold for genuinely good WLB at companies with 1,000+ UK reviews' },
      { type: 'h2', text: 'Scale matters' },
      { type: 'p', text: 'A WLB score of 4.5 from 40 reviews is interesting but not statistically meaningful (a good month or a few enthusiastic joiners can move it. The same score from 2,000 reviews is one of the strongest positive signals you can find in pre-joining research.' },
      { type: 'p', text: 'For smaller companies (under 200 employees), Glassdoor is less reliable and more volatile. Look at Indeed reviews as a cross-reference, and weight LinkedIn conversations with former employees more heavily than either.' },
      { type: 'h2', text: 'The questions it raises rather than answers' },
      { type: 'p', text: 'A low WLB score is a reason to investigate further, not automatically to walk away. "What drives the WLB score here?" is a completely reasonable question to ask a hiring manager. Their comfort level with the question) and the specificity of their answer (tells you almost as much as the score itself.' },
      { type: 'p', text: 'A high score with vague positive reviews ("great place to work!") is less reassuring than a high score with specific, detailed accounts of how flexibility actually operates day-to-day. Look for the latter.' },
      { type: 'h2', text: 'One more thing to look at' },
      { type: 'p', text: 'Read the lowest-rated recent reviews. Not to catastrophise, but to understand what the worst credible case is. Filter for people in roles similar to yours. If someone three levels below you in a support function had a terrible time, that\'s relevant but not necessarily predictive. If someone who was a Director of the function you\'re joining for 18 months left and wrote a detailed 1-star review, that is worth reading twice.' },
      { type: 'cta', text: 'Requite pulls Glassdoor WLB scores into every role analysis, alongside office days and parental leave data. Start free.' },
    ],
  },

  {
    slug: 'interview-the-interviewer',
    title: 'How to interview the interviewer without being annoying about it',
    subtitle: 'At senior level, the interview is supposed to go both ways. Most people don\'t make it go both ways. Here\'s how to change that) without making it weird.',
    date: '2026-04-07',
    readTime: 6,
    excerpt: 'Ten questions that tell you more about a company in forty minutes than most people learn in their first six months.',
    accent: '#5090f0',
    accentLight: '#EEF4FF',
    heroPattern: 'blue',
    tags: ['Interviews', 'Senior careers', 'Questions'],
    content: [
      { type: 'lead', text: 'At any level below Director, interviews are primarily an assessment. You are being evaluated. The power dynamic is clear and mostly one-directional. At Director level and above, this is no longer accurate (but most candidates don\'t behave as if they know it.' },
      { type: 'p', text: 'Senior hires are expensive, take time to onboard, and are hard to course-correct if they\'re wrong for the organisation. The hiring manager is not just checking whether you\'re capable. They\'re checking whether you\'re right for this specific role, culture, and moment. That means they want you to ask good questions. Candidates who ask no questions, or ask weak questions, create uncertainty.' },
      { type: 'h2', text: 'The questions that reveal the most, in order' },
      { type: 'p', text: '"What would make someone in this role brilliant rather than just good?") This forces a specific answer about what exceptional looks like, which is more informative than a job description. Pay attention to whether the answer is concrete or vague.' },
      { type: 'p', text: '"What\'s the hardest thing about working here that doesn\'t make it into the job posting?" (This gives interviewers permission to be honest and signals that you\'re not naive. Most interviewers will give you something real. Those who don\'t have told you something too.' },
      { type: 'p', text: '"Can you tell me about a decision made in the last year that you disagreed with) and how that disagreement was handled?" (This tells you about psychological safety, decision-making processes, and whether dissent is welcome or just tolerated.' },
      { type: 'p', text: '"What does the team I\'d be joining worry about?") Not what the company worries about. What your specific team worries about. This is usually more honest and more relevant.' },
      { type: 'p', text: '"Who in this organisation has the kind of career I might want to have in five years, and how did they get there?" (This tells you about internal mobility, what gets rewarded, and whether there\'s a realistic path.' },
      { type: 'quote', text: 'The best interview questions don\'t feel like tests. They feel like the start of a conversation you\'re genuinely interested in having. That\'s because the best candidates are genuinely interested) they\'re not just performing due diligence.' },
      { type: 'h2', text: 'The logistics questions that also matter' },
      { type: 'p', text: '"What time do people in this team typically finish on a weekday?" (Direct, low-stakes, high-signal. If the answer is vague or uncomfortable, file that away.' },
      { type: 'p', text: '"How does the team handle someone senior taking a proper lunch break / leaving on time consistently?") You\'re not asking for permission. You\'re checking whether the culture requires martyrdom.' },
      { type: 'p', text: '"What happened to the last person in this role?" (Sometimes the answer is straightforward: promotion, left for a competitor, role was restructured. Sometimes it\'s not. Either way, it\'s information.' },
      { type: 'h2', text: 'What to do with the answers' },
      { type: 'p', text: 'Write them down. Not in the interview (this can feel interrogative) but immediately afterwards. The quality of the answers you get is more diagnostic than the words themselves. Vague answers to concrete questions are a form of answer. Discomfort with questions about working culture is a form of answer.' },
      { type: 'p', text: 'Cross-reference what you hear with what Glassdoor says. When they align, you can have some confidence. When they diverge significantly, figure out which one you believe and why.' },
      { type: 'h2', text: 'The frame that makes it feel natural' },
      { type: 'p', text: 'The interviews that feel most uncomfortable for both parties are ones where the candidate is clearly running through a checklist. The ones that feel good) and lead to better hiring decisions (are ones where the candidate is genuinely trying to figure out whether this is right for them.' },
      { type: 'p', text: 'If you actually want to know the answer to the questions you\'re asking, you won\'t seem annoying. You\'ll seem like someone who takes their career seriously. Which is exactly the kind of person most organisations want in senior roles.' },
      { type: 'cta', text: 'Requite generates a full interview prep pack for any role in your pipeline) company research, likely questions, and STAR story frameworks. Start free.' },
    ],
  },

  {
    slug: 'parental-leave-interview-question',
    title: 'The parental leave question nobody asks in the interview',
    subtitle: 'Not "what\'s your policy" (that\'s the wrong question. Here\'s what to ask instead, and why the answer tells you far more than the policy document.',
    date: '2026-03-31',
    readTime: 5,
    excerpt: 'A company\'s parental leave policy is the start of the conversation, not the end of it. The real question is about what happens when you actually use it.',
    accent: '#50c878',
    accentLight: '#EDFCF3',
    heroPattern: 'green',
    tags: ['Parental leave', 'WLB', 'Interviews'],
    content: [
      { type: 'lead', text: 'Channel 4\'s parental leave policy) nine months at full pay for all parents (is genuinely exceptional. It also exists inside an organisation where one in three employees says the culture around actually taking that leave is complicated. The policy and the practice can diverge. Often, they do.' },
      { type: 'h2', text: 'Why "what\'s your policy?" is the wrong question' },
      { type: 'p', text: 'Every company in 2026 has a parental leave policy. Most of them are, at minimum, competitive with statutory requirements, and many go substantially beyond them. The policy is increasingly the minimum viable answer to the question of whether a company takes family seriously.' },
      { type: 'p', text: 'What the policy doesn\'t tell you: whether senior people actually use it at full length, whether careers have been visibly affected by taking it, whether there are informal norms that create pressure to return early, and whether the people who returned after extended leave were treated as fully equivalent to those who didn\'t take it.' },
      { type: 'h2', text: 'The question that gets to the practice' },
      { type: 'quote', text: '"Can you tell me about someone at Director level or above who\'s taken full parental leave recently, and what their experience of returning was like?"' },
      { type: 'p', text: 'This is the question. It is specific, reasonable, and impossible to fake a good answer to without the practice actually existing. Companies where senior people genuinely take full leave and return without penalty can answer this immediately) often with a name, a story, and visible pride.' },
      { type: 'p', text: 'Companies where the policy exists but the practice doesn\'t usually produce one of two responses: a long pause followed by a reference to the policy document, or an enthusiastic but non-specific answer about how supportive the culture is.' },
      { type: 'h2', text: 'The secondary questions worth asking' },
      { type: 'p', text: '"How is handover typically managed for someone taking extended leave?" (A company that has genuinely normalised parental leave has systems for this. A company that treats it as an exceptional disruption doesn\'t.' },
      { type: 'p', text: '"Is there any flexibility in how the leave is structured) for example, taking it in phases or combining it with part-time return?" (Enhanced shared parental leave and phased returns are markers of an organisation that\'s thought about this in depth rather than written a policy and moved on.' },
      { type: 'stat', label: '44%', detail: 'of senior professionals who took full parental leave reported their career progression was slower than peers who didn\'t, according to a 2024 McKinsey survey' },
      { type: 'h2', text: 'What to look for beyond the interview' },
      { type: 'p', text: 'LinkedIn is useful here. Search for the company and look at the career histories of people who joined around the same time as a potential parental leave. Did people at senior levels stay and continue progressing after career breaks? The data is imperfect but directional.' },
      { type: 'p', text: 'Glassdoor reviews filtered by "maternity", "paternity", or "parental leave" keywords can also be revealing) both the positive specifics ("took 9 months, came back to the same role with the same responsibilities") and the negative ones.' },
      { type: 'h2', text: 'When to have this conversation' },
      { type: 'p', text: 'It belongs in the second round, when you\'re talking to someone who works in the team rather than an initial HR screen. The person running the first-round screening often can\'t give you a specific answer even if they want to. The person who manages the team you\'d join can.' },
      { type: 'p', text: 'If parental leave is a genuine deciding factor for you, it also belongs in the explicit negotiation, not just the research phase. "Parental leave policy and how it\'s used in practice is important to me (can you send me specifics before I make a final decision?" is a completely reasonable ask at Director level.' },
      { type: 'cta', text: 'Requite verifies parental leave data for hundreds of UK employers and includes it in every role score. Start free.' },
    ],
  },

  {
    slug: 'director-job-hunting-is-different',
    title: 'Director-level job hunting is different. Here\'s how.',
    subtitle: 'The tactics that got you here don\'t work as well for what comes next. Understanding why is the first step to doing it better.',
    date: '2026-03-24',
    readTime: 7,
    excerpt: 'Most senior professionals use the same job search playbook they\'ve always used, and wonder why it\'s slower. There\'s a structural reason) and a structural fix.',
    accent: '#b060d8',
    accentLight: '#F8F0FF',
    heroPattern: 'purple',
    tags: ['Senior careers', 'Job hunting', 'Director'],
    content: [
      { type: 'lead', text: 'The job search market bifurcates sharply at the Director/VP level. Below it, most hiring is volume-oriented: companies post roles, candidates apply, processes are standardised. Above it, most hiring looks different (the process is longer, the sourcing is different, and the techniques that work lower down become less effective and sometimes actively counterproductive.' },
      { type: 'h2', text: 'Why the standard playbook breaks down' },
      { type: 'p', text: 'Applying to advertised roles via job boards is an entirely legitimate strategy at senior level) but it\'s less effective than it is for more junior searches, for a structural reason: a meaningful portion of Director+ roles are filled before they\'re advertised, through networks, through retained search firms, and through direct approaches.' },
      { type: 'p', text: 'This doesn\'t mean you should ignore advertised roles. It means that treating advertised roles as your only channel is leaving a substantial portion of the market invisible to you.' },
      { type: 'h2', text: 'The three channels that matter differently at senior level' },
      { type: 'p', text: 'Network referrals are more powerful and more efficient at senior level than they\'ve ever been in your career. Someone at Director+ level vouching for you isn\'t just a warm introduction (it\'s a credibility transfer that can get you to a first conversation with a hiring manager without a screening process. This is worth time investment to cultivate deliberately, not just during active searches.' },
      { type: 'p', text: 'Retained search firms (executive recruiters, as opposed to contingency recruiters) handle a significant proportion of Director and above searches. The right relationship with two or three good ones in your sector is worth more than a perfectly optimised LinkedIn profile. They are not incentivised to represent you well) they\'re incentivised to fill the role (but if you\'re a genuine fit for roles they\'re running, they\'re highly motivated to move things forward.' },
      { type: 'p', text: 'Targeted direct outreach) identifying specific companies you want to work for and reaching out to relevant people before a role is open (works at senior level in a way it doesn\'t earlier in a career. You have enough of a track record that the conversation isn\'t asymmetric.' },
      { type: 'quote', text: 'The Director-level job search is less about volume and more about precision. Five high-quality, genuinely targeted approaches will outperform fifty generic applications every time.' },
      { type: 'h2', text: 'The timeline problem' },
      { type: 'p', text: 'Senior searches take longer. The average time from first conversation to offer for Director+ roles in the UK is 12–16 weeks. This has a practical implication: if you start looking when you\'re desperate to leave, you\'ll either move too fast and make a worse decision, or you\'ll sustain a miserable job for four months while the process grinds forward.' },
      { type: 'p', text: 'The people who move into the best roles at senior level are almost universally those who started looking before they needed to. The search that begins from a position of reasonable stability) when you\'re curious about what\'s out there rather than urgently needing to be somewhere else (produces better outcomes.' },
      { type: 'stat', label: '14 weeks', detail: 'average time from first conversation to signed offer for Director-level UK searches) not counting time to get to the first conversation' },
      { type: 'h2', text: 'The thing nobody talks about: the emotional weight' },
      { type: 'p', text: 'Senior job searching is specifically psychologically difficult in a way that\'s not often acknowledged. You are accomplished enough to have a view about where you should be, which means rejection (when it comes) hits harder than it did at 28. You also have more at stake: teams that depend on you, a salary you\'ve built to, a professional identity that\'s partly constituted by your role.' },
      { type: 'p', text: 'The productive response to this is to make the search itself feel less consequential on any given day. Small, consistent actions (one conversation, one application, one reconnection per week) are more sustainable than intensive bursts of activity that burn you out and make a quiet week feel like failure.' },
      { type: 'h2', text: 'What to do this week if you\'re at Director level and considering moving' },
      { type: 'p', text: 'Tell two people in your network that you\'re curious about what\'s out there. Not that you\'re looking, which can create anxiety about your current role if it gets back (just that you\'re interested in having conversations. This is the lowest-risk activation of the network channel.' },
      { type: 'p', text: 'Update your LinkedIn to reflect your current role accurately and add two specific achievements from the last 18 months. This is both profile hygiene and a signal to the retained search firms who will read it.' },
      { type: 'p', text: 'Identify three companies you\'d genuinely want to work for. Research them specifically enough that you could have a 10-minute informed conversation about their current challenges and positioning. Then decide whether to approach them directly.' },
      { type: 'cta', text: 'Requite is built specifically for senior searches) scoring roles, tracking your pipeline, and helping you focus on the right opportunities. Start free.' },
    ],
  },

  {
    slug: 'two-week-rule-job-hunting',
    title: 'The two-week rule that changes how you job hunt',
    subtitle: 'A simple system for running an active job search without letting it consume your entire life (or your current role.',
    date: '2026-03-17',
    readTime: 5,
    excerpt: 'Most job searches fail not because people don\'t try hard enough, but because they try in the wrong pattern. Intensive activity followed by exhausted silence is worse than consistent, low-volume effort.',
    accent: '#e8c830',
    accentLight: '#FEFBEC',
    heroPattern: 'yellow',
    tags: ['Job hunting', 'Productivity', 'Systems'],
    content: [
      { type: 'lead', text: 'The typical job search pattern for senior professionals goes like this: energised phase) applications, LinkedIn updates, recruiter calls (for about three weeks. Then a rejection, or just exhaustion, followed by two weeks of doing nothing. Then re-engagement, usually from a slightly lower energy position than before. Then another dip. This pattern is extremely common and extremely ineffective.' },
      { type: 'h2', text: 'Why the burst pattern fails' },
      { type: 'p', text: 'Senior hiring processes move slowly. The average Director-level search takes 12–16 weeks from first contact to offer. A search conducted in intensive bursts with quiet patches in between is poorly matched to this timeline. You\'ll run out of energy before the process completes. You\'ll also miss the windows when things are actually moving) the period between an initial conversation and the company getting back to you is not the time to go quiet.' },
      { type: 'p', text: 'The burst pattern also has a hidden cost: it makes the search feel more consequential on any given day. When you\'ve done six applications in a week and heard nothing, that silence feels heavier than if you\'d done one thoughtful application and had a life the rest of the time.' },
      { type: 'h2', text: 'The two-week rule' },
      { type: 'p', text: 'The rule is simple: every two weeks, do one thing in each of three categories. No more is required. No less should be missed.' },
      { type: 'p', text: 'Category 1 (Active applications: one high-quality, role-specific application with a tailored CV and a brief covering note. Not ten generic applications. One careful one.' },
      { type: 'p', text: 'Category 2) Network: one conversation with someone relevant to where you\'re going. A former colleague, a peer at a company you\'re interested in, a recruiter who works in your sector. One coffee, one phone call, one LinkedIn message that becomes a conversation.' },
      { type: 'p', text: 'Category 3 (Research: identify one new company worth putting on your radar. Spend 30 minutes understanding what they do, whether they\'re hiring, and whether they could be worth approaching.' },
      { type: 'quote', text: 'This is six actions per month. It sounds like very little. It is more than the vast majority of active senior searchers sustain over a six-month period, because it\'s designed to be sustainable rather than impressive.' },
      { type: 'h2', text: 'What the rule does to your psychology' },
      { type: 'p', text: 'The most useful thing about this rule is that it gives you a clear, achievable definition of "doing enough." If you\'ve done one of each thing in the last two weeks, you are not failing. You can let the anxiety go. This matters particularly for senior professionals who are used to measuring their effectiveness by output volume, and who therefore feel guilty when the job search doesn\'t feel like work.' },
      { type: 'stat', label: '1 in 3', detail: 'senior professionals say the psychological pressure of job searching while employed caused them to make a worse decision than they\'d have made with more time) Korn Ferry, 2024' },
      { type: 'h2', text: 'When to break the rule' },
      { type: 'p', text: 'Break it when something real is moving. If you\'ve had a second-round interview and you\'re waiting to hear, it\'s fine to add another application to the pipeline so you\'re not holding your breath. If a company you\'ve been interested in suddenly announces a relevant role, add it (don\'t wait for the next two-week window.' },
      { type: 'p', text: 'The rule isn\'t a constraint. It\'s a floor. Treat it as the minimum viable level of effort required to keep a search genuinely alive, while leaving room for the rest of your life.' },
      { type: 'h2', text: 'One thing to add: a pipeline you can actually see' },
      { type: 'p', text: 'The two-week rule works best when it\'s attached to a visible pipeline) a simple list of where each opportunity stands, what the last action was, and what the next one is. Without this, it\'s easy to lose track of which ball is in whose court, and the search becomes reactive rather than managed.' },
      { type: 'cta', text: 'Requite is the pipeline and research tool built for senior searches. Track your applications, score new roles, and keep the right opportunities moving. Start free.' },
    ],
  },

  {
    slug: 'how-to-resign-well',
    title: 'How to resign well (when you\'ve finally found the right thing)',
    subtitle: 'The last 90 days in a role matter more than most people realise. How you leave shapes what comes next (and you only do it once.',
    date: '2026-03-10',
    readTime: 5,
    excerpt: 'The resignation conversation is almost always less dramatic than the anxiety that precedes it. But how you handle the next 90 days can either protect or damage everything you\'ve built.',
    accent: '#d84888',
    accentLight: '#FEF0F6',
    heroPattern: 'pink',
    tags: ['Career', 'Resignation', 'Leadership'],
    content: [
      { type: 'lead', text: 'After months of searching, interviewing, agonising, and finally finding the right thing) the resignation conversation tends to come as a relief. The dread beforehand is usually far worse than the reality. But what happens next, in the 90 days between handing in your notice and walking out the door, is where most people either cement or damage a professional legacy they\'ve spent years building.' },
      { type: 'h2', text: 'The conversation itself' },
      { type: 'p', text: 'Tell your manager before anyone else. Always. The fastest way to permanently damage a relationship with someone you\'ve worked closely with is for them to hear your resignation from someone else first.' },
      { type: 'p', text: 'Keep the initial conversation short and straightforward. You\'ve made a decision, you\'re giving appropriate notice, you\'re grateful for the experience. You don\'t owe them a detailed explanation of why you\'re leaving, and volunteering one often creates an opening for a conversation you didn\'t want to have.' },
      { type: 'p', text: 'If you like the person and the company, you can say so genuinely. "I\'ve loved working here, and this wasn\'t an easy decision" is honest and appropriate if it\'s true. If it\'s not true, say less.' },
      { type: 'h2', text: 'The counter-offer decision' },
      { type: 'p', text: 'It will probably come if you\'re good at your job. The right response depends on why you\'re leaving. If you\'re leaving because of money and nothing else, a counter-offer is worth considering seriously. If you\'re leaving for any other reason (culture, leadership, growth ceiling, work-life balance, general readiness for something different) a counter-offer changes the compensation but not the conditions. Research consistently shows the majority of people who accept counter-offers leave within 18 months anyway.' },
      { type: 'quote', text: 'The counter-offer is the company making the calculation that it\'s cheaper to pay you more than to replace you. That\'s a valid calculation on their part. It doesn\'t necessarily mean the working conditions that made you want to leave will change.' },
      { type: 'h2', text: 'The notice period as professional investment' },
      { type: 'p', text: 'The worst thing you can do in a notice period is mentally leave before you physically leave. The people who are remembered well are those who spent their notice period making things easier for whoever comes next (documentation, handover, introductions, closing out what they can close out.' },
      { type: 'p', text: 'This is not about martyrdom. It\'s about the fact that your professional world is smaller than it feels, and the people you work with now will reappear in your career in ways you can\'t predict. The colleague who seems irrelevant today might be a hiring manager in five years, or a reference you need, or someone who moves to a company you want to work for.' },
      { type: 'stat', label: '72%', detail: 'of senior professionals report that at least one career opportunity in the subsequent five years came from someone they worked with at a previous company' },
      { type: 'h2', text: 'What not to do' },
      { type: 'p', text: 'Don\'t use your notice period to litigate grievances. If there are things that have frustrated you, the exit interview is the right place for structured, constructive feedback) if you trust the person receiving it. The notice period itself is not the time for a broader reckoning.' },
      { type: 'p', text: 'Don\'t over-promise what you can hand over. An ambitious handover plan that you can\'t execute leaves more mess than a realistic one you actually complete.' },
      { type: 'p', text: 'Don\'t announce your new role publicly before you\'ve officially left the current one, particularly if you\'re in a senior position. This is a norm that varies by industry, but erring towards discretion is almost always the safer default.' },
      { type: 'h2', text: 'The exit interview' },
      { type: 'p', text: 'Be honest if you trust the HR team to use feedback constructively. Be diplomatic if you don\'t. "I wanted a new challenge" is true in almost every case and contains no information that anyone can misuse.' },
      { type: 'cta', text: 'You found the right thing. Requite helped you score it against what matters. Start the next one the same way, free trial, no card required.' },
    ],
  },

  // ── SET A: articles inspired directly by the lifestyle image slogans ──

  {
    slug: 'sunday-test-job-offers',
    title: 'The Sunday evening test (and what it is telling you)',
    subtitle: 'That low-grade dread between 5pm and 8pm is not a personal failing. It is information. Here is how to use it.',
    date: '2026-05-22',
    readTime: 4,
    excerpt: 'Most people treat the Sunday feeling as a weakness. It is not. It is one of the most reliable signals you have about whether your job is actually working for you.',
    accent: '#e8c830',
    accentLight: '#FEFBEC',
    heroPattern: 'yellow',
    heroImage: '/brand/lifestyle/ls-01.png',
    tags: ['Wellbeing', 'Job hunting', 'WLB'],
    content: [
      { type: 'lead', text: 'There is a moment that happens somewhere between 5pm and 8pm on a Sunday. You are fine, and then you are not. A low-grade dread settles in. Nothing you can point to exactly, just the knowledge that tomorrow is coming. Most people treat this as a personal failing. They are wrong. It is information.' },
      { type: 'h2', text: 'What the feeling is actually measuring' },
      { type: 'p', text: 'The Sunday feeling is not about being lazy or undisciplined. It is about the gap between the person you are outside of work and the version of yourself that shows up on Monday morning. When that gap is small, Sunday evenings are easy. When it is large, they are not.' },
      { type: 'p', text: 'Senior people often dismiss this because they have been taught that high performance requires discomfort. That is half true. High performance requires stretch and effort and sometimes pressure. It does not require low-grade dread as a standing condition.' },
      { type: 'p', text: 'There is a reasonable question to ask yourself: when was the last time you genuinely looked forward to a Monday? Not because something exciting was happening, but just because your work is the kind of work you actually like doing. If you have to think hard, that is worth noting.' },
      { type: 'h2', text: 'How to use it when evaluating a new role' },
      { type: 'p', text: 'When you are assessing a new job, most people think about the title, the salary, the company. Fewer people think seriously about what their Sunday evenings are going to feel like twelve months in.' },
      { type: 'p', text: 'Before you accept any offer, picture the role in its least exciting week. The week when there is no big project, no interesting meeting, just the ordinary rhythm of the job. How do you feel about that? If the answer is "fine, actually," that is a good sign.' },
      { type: 'p', text: 'The questions worth asking in an interview: what does a typical week look like? What are the expectations around response times outside of core hours? What happens if you need to leave at 5pm consistently for six months? The answers will tell you a lot. So will the way they answer.' },
      { type: 'h2', text: 'One thing to remember' },
      { type: 'p', text: 'No job eliminates the Sunday feeling entirely. Some pressure is real and some roles ask more of you than others. But there is a difference between a Sunday that has some tension in it because you care about your work, and a Sunday that feels like dreading something you cannot get out of. One is normal. The other is a sign something is wrong.' },
      { type: 'quote', text: 'The question is not whether Monday mornings are comfortable. It is whether you would choose this job again if you had to start over tomorrow.' },
      { type: 'p', text: 'Use that question. It is more useful than the salary figure, the title, or the commute.' },
      { type: 'cta', text: 'Score your next role properly before you accept it. Requite gives you the full picture in 30 seconds, salary, WLB, parental leave and all.' },
    ],
  },

  {
    slug: 'what-better-means-director-level',
    title: "What 'better' actually means when you have been around long enough to know",
    subtitle: 'At a certain point in a career, better stops being about the title. Here is what it actually becomes about.',
    date: '2026-05-21',
    readTime: 4,
    excerpt: "When you're starting out, better mostly means more money or a fancier title. Then at a certain point it shifts into something harder to articulate. You know it when you see it.",
    accent: '#50c878',
    accentLight: '#EDFCF3',
    heroPattern: 'green',
    heroImage: '/brand/lifestyle/ls-02.png',
    tags: ['Career', 'Director level', 'Job hunting'],
    content: [
      { type: 'lead', text: "When you are starting out, better mostly means more money or a fancier title. A few years in, it becomes about the work itself. Then, usually somewhere in your late thirties or forties, better shifts into something harder to articulate. You know it when you see it and you know it when it is missing." },
      { type: 'h2', text: 'The three things that actually matter at this level' },
      { type: 'p', text: 'Money still matters but it stops being the whole story. Most senior professionals say the same thing: once basic financial security is established, three things drive satisfaction at work.' },
      { type: 'p', text: 'First, autonomy. Not in a vague "I work independently" sense, but real decision-making latitude. The ability to shape how you do your job, who you work with, what you prioritise. Autonomy correlates more strongly with job satisfaction at senior levels than almost anything else.' },
      { type: 'p', text: 'Second, the quality of the people above you. Meaning the two or three people who actually make decisions about your career. You can have a great team, an interesting problem, and competitive pay, but if the person you report to is a poor manager or plays politics badly, none of that counts for much.' },
      { type: 'p', text: 'Third, and most overlooked: the way time is treated in the business. Does the culture genuinely respect that people have lives outside work? Not the policy documents, which are always fine, but the actual behaviour. Do people leave at reasonable times? Do they take their holidays? Does the business operate as though results are what matter, or is there a performance of busyness that everyone is expected to participate in?' },
      { type: 'h2', text: 'The practical way to assess this before you accept an offer' },
      { type: 'p', text: 'Ask to speak to someone who has been in the role or team for two to three years. Not the hiring manager. Someone junior enough that they are not yet strategic about what they tell you.' },
      { type: 'p', text: 'Ask them: what is the best thing about working here? What is the thing you wish you had known before you joined? What does a normal Friday afternoon look like? You will get real answers from these questions in a way you will not from the polished version of the company that the interview process presents.' },
      { type: 'quote', text: "Better is not a vague ambition. It is a specific checklist. The mistake is not writing yours down before the offer arrives." },
      { type: 'p', text: 'Write the checklist. Refer to it when the offer comes in. Do not let excitement or relief make you skip the items at the bottom.' },
      { type: 'cta', text: 'Requite scores every role against eight things that matter at this level. Try it free, seven days, no card.' },
    ],
  },

  {
    slug: 'ambitious-protect-your-evenings',
    title: 'You can still be ambitious without being owned by your employer',
    subtitle: 'Somewhere along the line, ambition and total availability got confused. They are not the same thing.',
    date: '2026-05-20',
    readTime: 4,
    excerpt: 'The idea that long hours are a proxy for commitment has cost a lot of people a lot of evenings. The research does not back it up either.',
    accent: '#a060d8',
    accentLight: '#F6F0FF',
    heroPattern: 'purple',
    heroImage: '/brand/lifestyle/ls-03.png',
    tags: ['WLB', 'Career', 'Wellbeing'],
    content: [
      { type: 'lead', text: 'Somewhere along the line, ambition and availability became confused. The idea took hold that if you really wanted it, you would be reachable at 9pm, that long hours were a proxy for commitment, that the people who got ahead were the ones who sacrificed the most. That idea has cost a lot of people a lot of evenings they are not getting back.' },
      { type: 'h2', text: 'The actual relationship between hours and output' },
      { type: 'p', text: 'Research consistently finds that output starts to decline after about 50 hours of work per week. Not gradually. Sharply. The quality of thinking drops, decisions get worse, and the ability to do genuinely creative or strategic work deteriorates significantly.' },
      { type: 'p', text: 'Senior jobs are largely made up of exactly the kind of thinking that suffers most from fatigue. Judgement, strategy, stakeholder management, reading a room correctly. None of these are improved by working until 10pm. Most of them are actively worsened by it.' },
      { type: 'stat', label: '50hrs', detail: 'The point at which weekly work hours start to produce sharply diminishing returns, according to Stanford research. Beyond 55 hours, output deteriorates so much that the extra hours produce almost no benefit.' },
      { type: 'h2', text: 'How to protect your evenings without managing perceptions all day' },
      { type: 'p', text: 'The practical version of this is simpler than most people make it. It is about being clear, early, in any new role, about how you work. Not aggressively. Not making it a condition of joining. Just being honest in the first few weeks about what your working patterns look like.' },
      { type: 'p', text: 'People take their cues from behaviour, particularly at senior level. If you work until 8pm in your first month, you are setting an expectation that will be hard to walk back.' },
      { type: 'p', text: 'The same applies in interviews. You are allowed to ask: what does work typically look like between 6pm and 8pm? What are the expectations around weekend communication? These are not unusual questions at senior level, and any organisation worth joining will answer them honestly.' },
      { type: 'quote', text: 'Ambition and a life outside work are not in conflict. The idea that they are is the most expensive piece of conventional wisdom in the professional world.' },
      { type: 'p', text: 'Pick your next role with your evenings in mind. You are not being precious. You are being serious.' },
      { type: 'cta', text: 'Requite verifies real WLB (Work Life Balance) data before you apply. Score any role in 30 seconds, free.' },
    ],
  },

  {
    slug: 'leaving-on-time',
    title: 'Clocking off: the surprisingly political act of leaving when your work is done',
    subtitle: 'Leaving the office at 5:30pm has become an act of mild rebellion in certain industries. This should not be the case.',
    date: '2026-05-19',
    readTime: 4,
    excerpt: "Leaving at 5:30pm when your work is done is the least controversial thing in the world. Yet somehow it has become a loaded act in a lot of workplaces. Here's what that tells you.",
    accent: '#5090f0',
    accentLight: '#EEF4FF',
    heroPattern: 'blue',
    heroImage: '/brand/lifestyle/ls-04.png',
    tags: ['WLB', 'Culture', 'Red flags'],
    content: [
      { type: 'lead', text: "Leaving the office at 5:30pm has become an act of mild rebellion in certain industries. You log off and you are aware that you are being observed doing it. Not by anyone in particular, just by the general consciousness of the building. This is strange, if you think about it carefully, because leaving at 5:30pm when your work is done is the least controversial thing in the world." },
      { type: 'h2', text: 'Why this happens and what it signals about a company' },
      { type: 'p', text: 'The performance of busyness is a cultural artefact. It emerges in organisations where output is hard to measure and visibility substitutes for results. If nobody really knows whether you are doing a good job or not, staying late at least signals that you are trying.' },
      { type: 'p', text: 'This is why the question about leave time is genuinely diagnostic. Ask at interview: do people tend to leave when their work is done, or do they tend to stay later? Frame it that way. Most interviewers will give you an honest answer because it does not feel like a loaded question.' },
      { type: 'p', text: 'If the answer is "people tend to stay later, we are quite an intensive culture," that tells you something precise. Not necessarily bad, but clear. You can decide whether that suits you.' },
      { type: 'p', text: 'If the answer involves phrases like "we all really care about the work," or "it varies but nobody is watching the clock," that also tells you something. Often that the honest answer to the first question would have been uncomfortable.' },
      { type: 'h2', text: 'What to do when leaving on time feels politically difficult' },
      { type: 'p', text: 'Start with the small version. Leave on time once or twice a week. See what actually happens. In most organisations, absolutely nothing happens. The catastrophe you anticipated, the perception of not caring, the subtle exclusion from important things, does not materialise.' },
      { type: 'p', text: 'If something does happen, that is genuinely useful information. It tells you more clearly than any other signal that this organisation has a culture you would eventually find suffocating. That is not a reason to stay and fight the culture. That is a reason to start looking.' },
      { type: 'quote', text: 'The best indicator of a healthy work culture is not the office design or the all-hands meetings. It is whether people leave when their work is done.' },
      { type: 'p', text: 'Find the places where that happens. They exist.' },
      { type: 'cta', text: 'Requite scores real WLB data alongside salary and parental leave. Seven days free, no card required.' },
    ],
  },

  {
    slug: 'relationship-cost-bad-job',
    title: 'The relationship cost of the wrong job (and why it never shows up on the spreadsheet)',
    subtitle: 'Most people assess a job offer using a fairly standard checklist. Almost nobody puts the impact on their relationship on it.',
    date: '2026-05-18',
    readTime: 5,
    excerpt: 'The relationship tax of overwork is well documented and well measured. It is also almost never part of the conversation when someone is deciding whether to take a role.',
    accent: '#d84888',
    accentLight: '#FEF0F6',
    heroPattern: 'pink',
    heroImage: '/brand/lifestyle/ls-07.png',
    tags: ['Wellbeing', 'WLB', 'Career'],
    content: [
      { type: 'lead', text: 'Most people assess a job offer using a fairly standard checklist. Salary, bonus, pension, equity if there is any. Commute time. Holiday allowance. Title. What almost no one puts on the list is the impact on their relationship.' },
      { type: 'h2', text: 'This sounds soft. It is not.' },
      { type: 'p', text: 'The relationship tax of overwork is well documented and well measured. Partners who consistently work more than 50 hours per week report lower relationship satisfaction, more conflict, and higher rates of the kind of slow disengagement that does not look like anything until one day it does.' },
      { type: 'p', text: 'This is not about blame. Overwork is often not chosen in any straightforward sense. People end up in jobs that consume more than they expected, for reasons that felt reasonable at the time. The issue is that the cost accumulates quietly, and by the time it is obvious, the accumulation is already substantial.' },
      { type: 'p', text: 'The irony is that the people most likely to sacrifice their home life for work are often the ones who are most motivated by the people they share that home life with. They are doing it for their family or their partner. And the very thing they are sacrificing is the relationship with the person they are doing it for.' },
      { type: 'h2', text: 'What to actually look at before you take the role' },
      { type: 'p', text: 'The question is not whether the job will be demanding. Most good senior jobs are. The question is whether the demands are predictable and bounded.' },
      { type: 'p', text: 'A role that asks a lot of you between 8am and 7pm is different from a role that asks a lot of you continuously, including evenings and weekends. Both might look the same from the outside. The difference is the quality of the time you have when you are not working.' },
      { type: 'p', text: 'Ask about this directly. What do people\'s evenings look like? Are there periods of the year that are particularly intensive? What happens if you need to be genuinely unavailable for a week?' },
      { type: 'quote', text: 'The no-plans evening, the meal you cook together on a Tuesday, the conversation that goes nowhere in particular. That is not a break from your real life. That is your real life.' },
      { type: 'p', text: 'Factor it into the checklist.' },
      { type: 'cta', text: 'Requite scores WLB (Work Life Balance) properly, not from policy pages, from real data. Start free.' },
    ],
  },

  // ── SET B: articles for the cropped lifestyle photos (text removed) ──

  {
    slug: 'reading-for-senior-professionals',
    title: 'What senior professionals actually read (and why most career books are a waste of time)',
    subtitle: 'The genre of career book with a striding figure on the cover sells very well. It does very little.',
    date: '2026-05-17',
    readTime: 4,
    excerpt: "There's a genre of career book that is extremely popular and almost entirely useless. Here is what actually moves the needle at director level and above.",
    accent: '#a060d8',
    accentLight: '#F6F0FF',
    heroPattern: 'purple',
    heroImage: '/brand/lifestyle/ls-01-photo.png',
    tags: ['Career', 'Director level', 'Development'],
    content: [
      { type: 'lead', text: "There is a genre of career book that is extremely popular and almost entirely useless. You can spot it by the cover, which features a person striding purposefully and looking off to the side. The title is usually a short word followed by an exclamation mark, or a bold claim about the number of habits you need. These books sell very well. They do not, as far as anyone can tell, make much difference." },
      { type: 'h2', text: 'What actually moves the needle at senior level' },
      { type: 'p', text: 'The reading that matters at director level and above is less likely to be found in the careers section. It is more likely to be found in history, psychology, or social science.' },
      { type: 'p', text: 'Understanding how organisations actually work, as opposed to how their official org charts suggest they work, requires a different kind of knowledge. The books that help are the ones about power, incentives, group behaviour, and how decisions really get made. Not the self-help versions of these things, but the actual research.' },
      { type: 'p', text: 'A few starting points: Philip Tetlock on expert prediction, Robert Cialdini on influence (the original, not the summaries), anything by Kahneman and Tversky. Not because they will teach you to negotiate salary better, but because they will make you harder to mislead.' },
      { type: 'h2', text: 'The reading habit that most high performers actually have' },
      { type: 'p', text: 'They read to think, not to be told what to do. The most useful professional reading gives you frameworks for making sense of situations, not prescriptions for what to do in them.' },
      { type: 'p', text: 'The practical version is simple. Spend twenty minutes before bed reading something that has nothing to do with your immediate work. A history of a company adjacent to yours. A book about a decision that went wrong and why. Something long-form that requires you to hold a complex argument in your head.' },
      { type: 'p', text: 'This is not a productivity approach. It is just what it looks like to be a senior person who thinks well.' },
      { type: 'quote', text: 'The leaders worth learning from are rarely reading the books about leadership. They are reading the books about how the world actually works.' },
      { type: 'p', text: 'Pick one this week. Not a career book. Something with a bit more depth. Your Sundays will be better for it.' },
      { type: 'cta', text: 'The right role gives you the headspace to think properly. Requite helps you find it, seven days free.' },
    ],
  },

  {
    slug: 'relocation-job-offer-checklist',
    title: 'Before you uproot your family for a role: the questions worth asking first',
    subtitle: 'Relocation packages look better on paper than they tend to feel in practice. Here is what most people forget to check.',
    date: '2026-05-16',
    readTime: 5,
    excerpt: 'The company covers moving costs. The salary is better. What rarely shows up in the conversation is the actual human cost of starting again somewhere new.',
    accent: '#5090f0',
    accentLight: '#EEF4FF',
    heroPattern: 'blue',
    heroImage: '/brand/lifestyle/ls-02-photo.png',
    tags: ['Job hunting', 'Career', 'Relocation'],
    content: [
      { type: 'lead', text: 'Relocation packages look better on paper than they tend to feel in practice. The company covers moving costs, sometimes offers a few months of bridging support, and the salary is usually better than what you would get locally. What rarely shows up in the conversation is the actual human cost of starting again in a city where nobody knows you.' },
      { type: 'h2', text: 'The things that are easy to underestimate' },
      { type: 'p', text: 'Your partner\'s career is the obvious one. If they are giving something up to make this move work, that has a cost, professionally and personally, that is very hard to calculate in advance.' },
      { type: 'p', text: 'Your children\'s school friendships. The support network of people who can help when something goes wrong. The GP who knows your history. The local pub where the people behind the bar know your order. These sound trivial. They are not.' },
      { type: 'p', text: 'None of this means do not move. Sometimes relocation is exactly the right thing. The point is to make the decision with full visibility of what you are trading, not just what you are gaining.' },
      { type: 'h2', text: 'The questions worth asking before you say yes' },
      { type: 'p', text: 'Can your partner work in this new location, and have they actually looked into it properly? What is the school situation, and have you spoken to anyone who has moved there with children of the same age? What is the cost of living differential, and have you run the actual numbers?' },
      { type: 'p', text: 'Is this role stable enough to justify uprooting your life? How long has the team been together? Does the company have a track record of relocating people and then letting them go within two years?' },
      { type: 'p', text: 'Have you spent at least a long weekend in the new city, not just passing through? Have you had an honest conversation with your partner about how they actually feel, not just whether they will support you?' },
      { type: 'quote', text: 'The best relocation decision is always the one made with open eyes about what you are giving up, not just what you are gaining.' },
      { type: 'p', text: 'One final question worth sitting with: would you be excited about this move if the salary were the same as your current role? If the honest answer is no, that is information worth taking seriously.' },
      { type: 'cta', text: 'Score any role against what actually matters before you make the call. Requite, seven days free.' },
    ],
  },

  {
    slug: 'the-6pm-question',
    title: 'The question to ask in every senior interview that most people forget',
    subtitle: 'There is one question that tells you more about a company than almost any other. Almost nobody asks it.',
    date: '2026-05-15',
    readTime: 4,
    excerpt: "Most people come out of senior job interviews having asked about strategy, team, and direction. Almost nobody asks the question that would tell them more than all of those combined.",
    accent: '#50c878',
    accentLight: '#EDFCF3',
    heroPattern: 'green',
    heroImage: '/brand/lifestyle/ls-03-photo.png',
    tags: ['Job hunting', 'Interviews', 'WLB'],
    content: [
      { type: 'lead', text: 'Most people come out of senior job interviews having asked about the strategy, the team, the challenges in the role, and where the business is heading. Almost nobody asks the question that would tell them more than all of those combined.' },
      { type: 'h2', text: 'What is it?' },
      { type: 'p', text: '"What does 6pm look like for someone in this role, on a typical Wednesday?"' },
      { type: 'p', text: 'Not a special Wednesday. Not a quarter-end Wednesday or a Wednesday when there is a big presentation the next day. Just a normal, medium Wednesday.' },
      { type: 'p', text: 'This question is specific enough that it is very hard to answer with polished HR language. It forces a real picture. Either you are on the sofa with your family by then, or you are at your desk with a takeaway, or you are in a meeting that probably did not need to happen, or you are on the train home having put in a full ten hours and feeling reasonably good about it.' },
      { type: 'h2', text: 'How to read the answer' },
      { type: 'p', text: 'If the person interviewing you looks slightly uncomfortable before answering, that is information. If they answer confidently with "people tend to wrap up by then," that is encouraging. If the answer is "it depends," ask what it depends on. If they say "we are an intense culture but it is worth it," you now know what you are getting into.' },
      { type: 'p', text: 'The most revealing version is when they start talking about the company\'s commitment to WLB (Work Life Balance) rather than actually answering the question. Good policies and actual behaviour are two entirely different things. The question is designed to surface the behaviour.' },
      { type: 'p', text: 'Follow it up with: "What about Friday evenings? Is there much happening then?" Two data points are more useful than one.' },
      { type: 'h2', text: 'Why more people do not ask it' },
      { type: 'p', text: 'Because it feels slightly risky, as though you are signalling that you are not fully committed before you have even started. That is the wrong way to think about it.' },
      { type: 'p', text: 'At senior level, you are expected to know what you want from a role. A director who does not ask about their working conditions in an interview is either very confident they know the answers already, or they are not being fully honest with themselves about what matters.' },
      { type: 'quote', text: 'The interview is a two-way process. That is said a lot and mostly not believed. The 6pm question is the fastest way to make it real.' },
      { type: 'p', text: 'Ask it. The companies worth joining will be pleased you did.' },
      { type: 'cta', text: 'Requite verifies WLB data from real sources before you even get to interview. Score any role free.' },
    ],
  },

  {
    slug: 'hybrid-working-red-flags',
    title: 'Hybrid working red flags: how to tell who actually means it before you sign',
    subtitle: 'Every company has a hybrid policy. Most of them mean something rather different in practice.',
    date: '2026-05-14',
    readTime: 5,
    excerpt: "The gap between a company's written hybrid policy and what actually happens is where a lot of people get a very unpleasant surprise in their first six months.",
    accent: '#e8c830',
    accentLight: '#FEFBEC',
    heroPattern: 'yellow',
    heroImage: '/brand/lifestyle/ls-04-photo.png',
    tags: ['Flexible working', 'Red flags', 'Job hunting'],
    content: [
      { type: 'lead', text: 'Every company has a hybrid working policy. Most of them mean "we would really prefer you in most of the time but we have written this policy to say otherwise." The gap between what is written and what is true is where a lot of people get a very unpleasant surprise in their first six months.' },
      { type: 'h2', text: 'The phrases that should give you pause' },
      { type: 'p', text: '"Flexible but collaborative" tends to mean: we do flexible for junior people but there is an unspoken expectation that senior people are visible.' },
      { type: 'p', text: '"We trust our people to manage their own time" often means: we have not had the honest conversation about what we actually expect, so be prepared for it to emerge gradually and not in your favour.' },
      { type: 'p', text: '"We have just refreshed our hybrid policy" is frequently code for: the previous policy was too permissive and we have tightened it. Ask when it was last changed and what changed.' },
      { type: 'p', text: '"Our leadership team are great role models for flexible working" is worth testing. Ask who specifically. Before you accept, do some basic research. Are they visibly in the office most of the time? None of this is foolproof, but it is better than taking the policy document at face value.' },
      { type: 'h2', text: 'The questions that give you real answers' },
      { type: 'p', text: 'Ask to speak to someone who joined in the last eighteen months and is not senior enough to have had their words pre-approved. Ask them: how often are you expected in? What happens if you are working from home and miss something?' },
      { type: 'p', text: 'Ask the hiring manager: how many days a week are you personally in the office? Ask it directly, about them, about their actual behaviour. The answer should match whatever they have told you the policy is.' },
      { type: 'p', text: 'Ask what happens in the first few months. Many companies have informal expectations that new joiners are in more often early on. That is not always unreasonable, but it is worth knowing in advance.' },
      { type: 'h2', text: 'One thing that is often overlooked' },
      { type: 'p', text: 'Check whether the office is actually good to work in. A hybrid policy only works if the in-office days are meaningfully better than working from home. If the office is poorly set up for focused work, the days you spend there will feel like a significant cost rather than a benefit.' },
      { type: 'quote', text: 'Before you sign, ask yourself: does the commute feel like a reasonable trade-off for the in-office days as described? If the honest answer is no, do not assume it will feel different once you are in the role.' },
      { type: 'cta', text: 'Requite checks office day expectations alongside WLB data, salary, and parental leave. Score free.' },
    ],
  },

  {
    slug: 'sleep-and-senior-performance',
    title: 'Senior leaders are chronically undersleeping. Here is what the research says it costs them.',
    subtitle: 'Sleep is the health behaviour with the strongest evidence base and the least social support for doing it properly.',
    date: '2026-05-13',
    readTime: 5,
    excerpt: 'You can tell a colleague you have been to the gym and they will nod approvingly. Tell them you got eight hours of sleep and they will look at you like you are slightly irresponsible.',
    accent: '#d84888',
    accentLight: '#FEF0F6',
    heroPattern: 'pink',
    heroImage: '/brand/lifestyle/ls-07-photo.png',
    tags: ['Wellbeing', 'Performance', 'Career'],
    content: [
      { type: 'lead', text: 'Sleep is the health behaviour with the strongest evidence base and the least social support for doing it properly. You can tell a colleague you have been to the gym and they will nod approvingly. You can tell them you got eight hours of sleep last night and they will look at you like you are either extremely lucky or slightly irresponsible.' },
      { type: 'h2', text: 'What the research actually shows' },
      { type: 'p', text: 'Matthew Walker\'s research at UC Berkeley is the most comprehensive available. The findings are not subtle. Sleep below six hours per night for more than a few consecutive days produces impairment equivalent to being legally drunk. Decision-making, judgement, emotional regulation, and the ability to read social situations all deteriorate in measurable ways.' },
      { type: 'p', text: 'For senior roles, where almost everything you do depends on those exact capacities, this is not a peripheral concern. A senior leader operating on five hours of sleep is making worse calls than the same leader on eight hours. The confidence tends to go in the opposite direction to the competence, which makes the problem invisible from the inside.' },
      { type: 'stat', label: '6hrs', detail: 'The threshold below which Matthew Walker\'s research shows cognitive impairment equivalent to legal intoxication. Most senior professionals who claim to function fine on six hours are, according to the same research, not in a position to accurately assess their own impairment.' },
      { type: 'h2', text: 'What this has to do with job choice' },
      { type: 'p', text: 'Some jobs are structurally incompatible with adequate sleep. The hours, the travel, the on-call expectations, or the culture of late-night communication mean that consistently getting seven to eight hours is simply not possible while doing the job properly.' },
      { type: 'p', text: 'This is worth knowing before you take the role, not six months in when you are wondering why everything feels harder than it used to.' },
      { type: 'p', text: 'Ask directly: what are the travel expectations? Are there periods when international calls or early morning meetings are regular? What is the expectation around late-night email? None of these are disqualifying on their own. Some phases of a career require it. The question is whether this is a phase or a standing condition.' },
      { type: 'h2', text: 'The practical version' },
      { type: 'p', text: 'You do not need to read all the research to use this. Track your sleep honestly for two weeks. Then notice your performance in meetings, your patience with difficult people, your ability to think clearly under pressure.' },
      { type: 'p', text: 'If you are regularly under seven hours and you are in a demanding role, you are not performing at the level you think you are. Nobody is.' },
      { type: 'quote', text: 'The most underrated performance intervention available to every senior professional costs nothing and takes no extra time. It is just sleeping enough. Almost nobody does it.' },
      { type: 'cta', text: 'The right role leaves you enough room to actually perform at your best. Requite helps you find it, free for seven days.' },
    ],
  },
]
